# ----------- CONFIGURABLE START -----------
title:            "Test|English Stuying"
description:      "welcom"
url:              https://www.myword.cf # 域名
signoff:          "BD" # Your name
facebook_appid:   NA
google_analytics: NA
share:            true 
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         Words
    url:          /words
    external:     false
  - name:         Sentences
    url:          /sentences
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
